env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  eqeqeq: [error, always]
  no-unused-vars: off
  quotes: [error, single, { avoidEscape: true }]
  semi: [error, never]
